### ISSUE TITLE
Responsive Web Design Learn CSS Colors by Making a Set of Colored Markers bug

### ISSUE THREAD

**Issue by SamTada** [freeCodeCamp/mobile#1084]
Bug

In
➞ step 72
'Set the sleeve element's background-color to white'
 
and in
➞ step 81
'In the .sleeve Css rule add the border-left-color property to black'

answers that were clearly correct were not accepted.

The only way to complete those two steps was in the browser, in spite of the forceable zoom feature.
(also, maybe you could look into exempting media with smaller screen sizes from that?)

 - Device: Redmi Note 10 Pro
 - OS: Android 13
 - Browser: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36
 - Latest version of the app 4.1.0

**Comment by NamanAg0502** [comment]
Hey,

> Step 72 did not contained any bug

<img width="200" alt="Screenshot 2023-08-17 at 3 05 06 AM" src="https://github.com/freeCodeCamp/mobile/assets/76512364/49600efa-79be-4b6d-a382-ea83b81cb998">

> Step 81 is not working

<img width="353" alt="Screenshot 2023-08-17 at 3 13 57 AM" src="https://github.com/freeCodeCamp/mobile/assets/76512364/5851f7f8-e955-4e78-83da-013dfe83557a">


I would like to work on this.

**Comment by Nirajn2311** [comment]
Hi @SamTada , both challenges are passing with the correct solutions. Maybe if you could show the code you used for submitting the challenge then we could know why it failed.

> The only way to complete those two steps was in the browser, in spite of the forceable zoom feature.
(also, maybe you could look into exempting media with smaller screen sizes from that?)

Could you explain this part? I didn't quite get you on the "forceable zoom feature"

**Comment by Nirajn2311** [comment]
@NamanAg0502 That's strange, that's exactly the same solution I wrote for step 81 and it passed for me. Could you share the whole CSS code or try submitting again after resetting the cache(Open the drawer when you first open the open the app, click `Settings` and you'll see a `Reset Cache` option).

**Comment by opxdelwin** [comment]
step 81 clearly works for me, we'd need more insights on your solution @SamTada

**Comment by Fran5ois** [comment]
Hello all, not my issue is well related to this topic, but here the problwm I get:
On "Responsive Web Design Learn CSS Colors by Making a Set of Colored Markers" course I the submission has stopped working since step 51 in tge android app. When I submit the blue check mark turns into a the rotating animation foe a fraction of a second and goes back to the blue check mark with no prompt. 
I managed to submit the same code on the browser version though.
Here is what I tried with no effect:
- updated the app
- restarted the app
- restarted my phone (galaxy note 10plus)
- cleared cache
- cleared data
- cleared chache from within the app
- uninstalled and installed the app again
- ... several time each :]

Would it be possible that commucation from app to server fails?

Would anyone have a solution? The browser version on mobile is quite unusable, and the app rocks... I would love it back
