### ISSUE TITLE
Documentation on how to get started on the mobile app

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#16]
This is what I noted down while I was setting up Flutter and Dart on my system.

# Flutter and Dart setup

## Windows, Linux, Mac
* Follow the official guide - https://flutter.dev/docs/get-started/install - I can confirm their guide worked without any issues on Windows 10 Home with and without WSL

## Notes for users Mac with Apple Silicon
Follow the official guide but make the below 2 changes:
* Install the Beta build of Android Studio for Apple Silicon - Android Studio Arctic Fox (2020.3.1) Beta 5
Link for download - https://developer.android.com/studio/archive
* Download the "arm64" version of SDKs
* If "flutter doctor" gives an error about Java not found, then the fix for it is to copy the folder "/Applications/Android Studio Preview.app/Contents/jre/Contents" to "/Applications/Android Studio Preview.app/Contents/jre/jdk/Contents" .
Source - https://github.com/flutter/flutter/issues/76215#issuecomment-864407892

**Comment by Nirajn2311** [comment]
Yes, I'm working on that currently. I'm documenting everything I do:

**Comment by Nirajn2311** [comment]
This is what I noted down while I was setting up Flutter and Dart on my system.

# Flutter and Dart setup

## Windows, Linux, Mac
* Follow the official guide - https://flutter.dev/docs/get-started/install - I can confirm their guide worked without any issues on Windows 10 Home with and without WSL


## Notes for users Mac with Apple Silicon
Follow the official guide but make the below 2 changes:
* Install the Beta build of Android Studio for Apple Silicon - Android Studio Arctic Fox (2020.3.1) Beta 5
Link for download - https://developer.android.com/studio/archive
* Download the "arm64" version of SDKs
* If "flutter doctor" gives an error about Java not found, then the fix for it is to copy the folder "/Applications/Android Studio Preview.app/Contents/jre/Contents" to "/Applications/Android Studio Preview.app/Contents/jre/jdk/Contents" .
Source - https://github.com/flutter/flutter/issues/76215#issuecomment-864407892
