### ISSUE TITLE
Add Computer Science Flash Cards

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/mobile#8]
We want to add a feature that borrows inspiration and the dataset from the awesome work already done in here: https://github.com/jwasham/computer-science-flash-cards

As a user I want to be able to:

- [ ] browse through a list of flash-card categories, which group cards in logical categories.
- [ ] browse through the cards in a group.
- [ ] look at the question on the card.
- [ ] flip the card to look at the solution / answer.
- [ ] tag a card with a difficulty level (easy/hard/very-hard) as per my comfort & will.
- [ ] browse through cards of a certain difficulty level I tagged.
- [ ] hide cards completely in an archive area.
- [ ] create and update new custom groups (other than the standard set)
- [ ] create and update new custom cards (other than the standard set)
- [ ] add cards to the custom groups.
- [ ] delete cards to the custom groups.

**Comment by QuincyLarson** [comment]
@raisedadead @Sembauke We already have this in the form of DeveloperQuiz.org. I recommend we expand the functionality of this website instead of building a separate tool.

I know this is from nearly a year ago, but Sem mentioned this issue to me. (This is not super high priority.)

This application was built by @jdwilkin4 and @deniselemonaki. If you want to share feedback for how similar this is to your vision of flashcards, we could come up with some specific user stories to build out.

This would also be a cool thing to build into the mobile app at some point.

**Comment by deniselemonaki** [comment]
The application was built by @jdwilkin4  and @estefaniacn. I was not involved with the design and build.
